### ISSUE TITLE
Unhandled exception UWP 4.4.2

### ISSUE THREAD

**Issue by Orma07** [alexrainman/CarouselView#205]
I'm not able to load my carousel view on UWP, on Android works fine, but in UWP i got this exception in App.g.i.s:
Exception = {System.NullReferenceException: Object reference not set to an instance of an object.}
  at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.InsertPage(Object item, Int32 position)
   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.<ItemsSource_CollectionChanged>d__13.MoveNext()

**Comment by alexrainman** [comment]
This is related to another issue. Releasing a fix today.
