### ISSUE TITLE
MissingMethodException : Adding same object to Itemsource

### ISSUE THREAD

**Issue by douni327** [alexrainman/CarouselView#462]
Hi. 

I always appreciate your awesome solution.

I have an issue with below code. Did I have wrong code? 

Would you please give it a check! Thanks.

<C#>
List<Image> images = new List<Image>();
Image image = new Image { Source = ImageSource.FromFile("logo") };
for(int i = 0; i < 5; i++)
{
     images.Add(image);   // Adding same object to ItemSource
}
myCarousel.ItemsSource = images;

Exception Error :
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.ImageRenderer from native handle 0xbea39064 (key_handle 0x93dec86).
---> System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.ImageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership
---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
  at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
  at java.lang.Error: Java callstack:
  at at md507f625f62cafec6e81efe0279defe3bb.CarouselViewRenderer_PageAdapter.n_destroyItem(Native Method)
  at at md507f625f62cafec6e81efe0279defe3bb.CarouselViewRenderer_PageAdapter.destroyItem(CarouselViewRenderer_PageAdapter.java:57)
  at at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:505)
  at at md58432a647068b097f9637064b8985a5e0.TabbedPageRenderer.n_onLayout(Native Method)
  at at md58432a647068b097f9637064b8985a5e0.TabbedPageRenderer.onLayout(TabbedPageRenderer.java:73)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
  at at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onLayout(Native Method)
  at at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onLayout(NavigationPageRenderer.java:65)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
  at at md58432a647068b097f9637064b8985a5e0.MasterDetailContainer.n_onLayout(Native Method)
  at at md58432a647068b097f9637064b8985a5e0.MasterDetailContainer.onLayout(MasterDetailContainer.java:53)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
  at at md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.n_onLayout(Native Method)
  at at md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.onLayout(MasterDetailPageRenderer.java:68)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.n_onLayout(Native Method)
  at at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.onLayout(PlatformRenderer.java:63)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
  at at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
  at at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
  at at android.view.View.layout(View.java:17637)
  at at android.view.ViewGroup.layout(ViewGroup.java:5575)
  at at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
  at at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
  at at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
  at at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
  at at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
  at at android.view.Choreographer.doCallbacks(Choreographer.java:686)
  at at android.view.Choreographer.doFrame(Choreographer.java:621)
  at at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
  at at android.os.Handler.handleCallback(Handler.java:751)
  at at android.os.Handler.dispatchMessage(Handler.java:95)
  at at android.os.Looper.loop(Looper.java:154)
  at at android.app.ActivityThread.main(ActivityThread.java:6119)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <f22a0e61648d492d93a9f4b449a72df2>:0
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <f22a0e61648d492d93a9f4b449a72df2>:0
  --- End of inner exception stack trace ---

**Comment by alexrainman** [comment]
By the stacktrace, this issue is not related to the carousel.

**Comment by alexrainman** [comment]
I don't think i can fix this as in Android, once you add a view to a ViewGroup, it already has a parent and cannot be added again.

**Comment by alexrainman** [comment]
As a workaround, create multiple instances of FFImageLoading CachedImage. They will be different views and it will work as expected but with the difference that all them will point to same cached android drawable.
