### ISSUE TITLE
[UWP] Crash when calling FreshMVVM RaisePageWasPopped

### ISSUE THREAD

**Issue by Ruddy2007** [alexrainman/CarouselView#469]
This is a bit random but I seem to be struggling with what this could be! I have a carousel view on pretty much all my applications pages (my app uses a navigation page) but when I call RaisePageWasPopped in FreshMVVM I get the following crash. 

```
-		$exception	{System.NullReferenceException: Object reference not set to an instance of an object.
   at CarouselView.FormsPlugin.Abstractions.IEnumerableExtensions.GetCount(IEnumerable e)
   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.SetArrowsVisibility()
   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.Element.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Xamarin.Forms.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property)
   at Xamarin.Forms.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged)
   at Xamarin.Forms.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)
   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.Grid.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)
   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.TemplatedView.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)
   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.ContentView.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.TemplatedPage.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)
   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.Page.OnBindingContextChanged()
   at Xamarin.Forms.ContentPage.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at FreshMvvm.FreshBasePageModel.RaisePageWasPopped()
   at MyApp.Services.Navigation.FreshMvvmCustomNavigation.PopToPageIndex(Int32 pageIndex, Boolean animate)
   at FreshMvvm.PageModelCoreMethods.<PopToPageIndex>d__14.MoveNext()}	System.NullReferenceException
```
Note that there isn't any custom code for that method, I just call it when popping pages int he navigation stack. I'm hoping someone can help me out and point me in the right direction. This seems completely random to me.

**Comment by alexrainman** [comment]
I have 0 experience with FreshMVVM.

**Comment by alexrainman** [comment]
Can you provide a demo?

**Comment by Ruddy2007** [comment]
@alexrainman Will try to put one together soon and get back to you.

**Comment by anson3923** [comment]
facing same problem when in master detail app, listview menu item selected 
 navigationDrawer.ContentView = new Page1().Content;
 and you will see the error (Exception thrown: 'System.NullReferenceException

**Comment by alexrainman** [comment]
I can see the main page with no content but I can't see the crash.

**Comment by Ruddy2007** [comment]
I have hooked in your project so I can see a little bit of what is going on. From what I can see we fallover here:

```
public static int GetCount(this IEnumerable e)
{
     var enumerator = e.GetEnumerator();
     int i = 0;
     while (enumerator.MoveNext())
     {
          i++;
     }
     return i;
}
```

`e` is null and it falls over on `e.GetEnumerator();`. Hope this gives you a little more to go on while I still look into this.

**Comment by alexrainman** [comment]
This definitely helps.

**Comment by Ruddy2007** [comment]
Manage to get anywhere with this? Still a hide issue for me.
