### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by mateuszroszczyk** [alexrainman/CarouselView#91]
When I swipe CarouselView back and forth I reach a point where my app crashes with OutOfMemoryException on Android (I don't know if it happens on other platforms).

Stack trace:

```
04-09 19:21:38.780 I/MonoDroid( 2658): UNHANDLED EXCEPTION:
04-09 19:21:38.794 I/MonoDroid( 2658): Java.Lang.OutOfMemoryError: Failed to allocate a 2514252 byte allocation with 761008 free bytes and 743KB until OOM
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x0001b] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Android.Graphics.BitmapFactory.DecodeStream (System.IO.Stream is) [0x0001e] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Graphics.BitmapFactory.cs:723 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Android.Graphics.BitmapFactory+<DecodeStreamAsync>c__AnonStorey9.<>m__0 () [0x00000] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Graphics.BitmapFactory.cs:732 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x00012] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:680 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
04-09 19:21:38.794 I/MonoDroid( 2658): --- End of stack trace from previous location where exception was thrown ---
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Xamarin.Forms.Platform.Android.StreamImagesourceHandler+<LoadImageAsync>d__0.MoveNext () [0x000cd] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\StreamImagesourceHandler.cs:17 
04-09 19:21:38.794 I/MonoDroid( 2658): --- End of stack trace from previous location where exception was thrown ---
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Xamarin.Forms.Platform.Android.ImageRenderer+<UpdateBitmap>d__9.MoveNext () [0x000fe] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\ImageRenderer.cs:91 
04-09 19:21:38.794 I/MonoDroid( 2658): --- End of stack trace from previous location where exception was thrown ---
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-09 19:21:38.794 I/MonoDroid( 2658):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/4009/9578cdcd/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:35 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4009/9578cdcd/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
04-09 19:21:38.794 I/MonoDroid( 2658):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Java.Lang.IRunnable.cs:81 
04-09 19:21:38.794 I/MonoDroid( 2658):   at (wrapper dynamic-method) System.Object:1a3f60c5-6f97-4624-bd5c-4d44fc40627d (intptr,intptr)
04-09 19:21:38.794 I/MonoDroid( 2658):   --- End of managed Java.Lang.OutOfMemoryError stack trace ---
04-09 19:21:38.794 I/MonoDroid( 2658): java.lang.OutOfMemoryError: Failed to allocate a 2514252 byte allocation with 761008 free bytes and 743KB until OOM
04-09 19:21:38.794 I/MonoDroid( 2658): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
04-09 19:21:38.794 I/MonoDroid( 2658): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
04-09 19:21:38.794 I/MonoDroid( 2658): 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
04-09 19:21:38.794 I/MonoDroid( 2658): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
04-09 19:21:38.794 I/MonoDroid( 2658): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:649)
```

Xaml:

```xaml
<cv:CarouselViewControl ItemsSource="{Binding CurrentStay.Hotel.Images}"
                        Orientation="Horizontal"
                        CurrentPageIndicatorTintColor="White"
                        PageIndicatorTintColor="Gray"
                        ShowIndicators="True"
                        Grid.Row="0">
    <cv:CarouselViewControl.ItemTemplate>
        <DataTemplate>
            <Grid>
                <Image Aspect="AspectFill"
                       Source="{Binding Url}" />
                <Image Source="{customItems:ImageResource Resources.Effects.shadow-wide.png}"
                       Aspect="AspectFill" />
            </Grid>
        </DataTemplate>
    </cv:CarouselViewControl.ItemTemplate>
</cv:CarouselViewControl>
```

Xamarin.Forms 2.3.3.193
CarouselView 3.1.1

**Comment by alexrainman** [comment]
Take a look at the repo Readme. This is not the carousel control itself. If you are going to use it with images you have to use FFImageLoading or dispose them manually or you will get outofmemory exception.

**Comment by alexrainman** [comment]
This repo will provide you an idea how to use FFImageLoading with CarouselView: https://github.com/alexrainman/TabbedCarouselView/tree/master/TabbedPageCarousel

**Comment by mateuszroszczyk** [comment]
@alexrainman I've already got it working but thanks :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
